version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --include=dev
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build